version: '3.8'

services:
  web:
    build: .
    command: gunicorn scrapping_ecommerce.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
