version: '3.8'

services:
  web:
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=db+${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    entrypoint: ""
    command: celery -A scrapping_ecommerce worker -l info
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=db+${DATABASE_URL}
    depends_on:
      - redis
      
  celery-beat:
    build: .
    entrypoint: ""
    command: celery -A scrapping_ecommerce beat -l info
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=db+${DATABASE_URL}
    depends_on:
      - redis
