version: '3.8'

services:
  web:
    build: .
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn scrapping_ecommerce.wsgi:application --bind 0.0.0.0:5001"
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
      - redis
    ports:
      - "5001:5001"

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A scrapping_ecommerce worker -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      
  celery-beat:
    build: .
    command: celery -A scrapping_ecommerce beat -l info
    env_file: .env
    volumes:
    - .:/app
    depends_on:
      - db
      - redis
      
volumes:
  mysql_data:
  static_volume:
